### ISSUE TITLE
Strip backticks before comparing to ignore file

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#39]
It would be nice for
```toml
[ignore]
"xyz" = ["abc"]
```
to match both `[xyz]: abc` and ``[`xyz`]: abc``. Otherwise you have to make two entries for the same link.
