### ISSUE TITLE
Ignore links per-crate?

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#40]
Right now you can ignore links globally:

```toml
[ignore]
"name" = [ "link 1" ]
```
and per-file:
```
["tracing-core/src/lib.rs"]
"`downcast_ref`" = [ "#method.downcast_ref" ]
```
but not per crate. It would be nice to be able to say "ignore links to `String`, but only in the `core` crate".

I'm not sure how to fit that in to the existing syntax - I think we might have hemmed ourselves in by getting too clever with the keys. Maybe something like this?

```toml
[[crate]]
name = "core"
"String" = "../../std/str/struct.String.html"
```

That means you can't ignore a `name` link I think, but I'm not sure what other syntax intra-conv could use.
